[package]
name = "rails_fast_attributes"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libcruby-sys = { path = "/Users/sean/builds/helix/crates/libcruby-sys" }
libc = "0.2.0"
